init:
  - git config --global core.autocrlf input

environment:
  matrix:
    - nodejs_version: "0.11.14"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install -g npm@next
  - npm install
  - npm install -g shark-cli

test_script:
  - node --version
  - npm --version
  - ps: "npm test # PowerShell" # Pass comment to PS for easier debugging
  - cmd: npm test

build: off
version: "{build}"